// ============================================================
// POPPINS CORP — Cross-Department Workflows
// Flujos de trabajo que cruzan departamentos
// ============================================================

import { Workflow } from '../types';

export const workflows: Workflow[] = [
  // ── CONTRATACIÓN (New Hire) ──────────────────────────────
  {
    id: 'wf-new-hire',
    name: 'Proceso de Contratación',
    description: 'Flujo completo desde la solicitud de headcount hasta el primer día del empleado. Involucra HR, Finance, Legal, IT y el departamento solicitante.',
    departments: ['hr', 'finance', 'legal', 'technology'],
    trigger: 'Solicitud de headcount aprobada por CEO/COO',
    sla: '25 días hábiles desde aprobación hasta día 1',
    steps: [
      {
        id: 'wf-nh-1',
        order: 1,
        name: 'Aprobación de headcount y presupuesto',
        description: 'CFO valida que hay presupuesto para la posición. CEO aprueba si es senior+.',
        responsibleAgent: 'cfo',
        approvers: ['ceo'],
        nextStep: 'wf-nh-2',
        conditions: ['Presupuesto disponible', 'Posición justificada'],
        requiredTools: ['Financial Database'],
      },
      {
        id: 'wf-nh-2',
        order: 2,
        name: 'Definición del perfil y publicación',
        description: 'Recruitment Manager define el perfil con el hiring manager y publica la posición.',
        responsibleAgent: 'hr-recruitment-manager',
        nextStep: 'wf-nh-3',
        conditions: ['Job description aprobado'],
        requiredTools: ['BUK Organization', 'LinkedIn Integration'],
      },
      {
        id: 'wf-nh-3',
        order: 3,
        name: 'Proceso de selección',
        description: 'Screening, entrevistas técnicas y culturales, evaluaciones.',
        responsibleAgent: 'hr-recruitment-manager',
        nextStep: 'wf-nh-4',
        requiredTools: ['TestGorilla'],
      },
      {
        id: 'wf-nh-4',
        order: 4,
        name: 'Oferta y negociación',
        description: 'Se genera la oferta salarial. CHRO aprueba el paquete de compensación.',
        responsibleAgent: 'chro',
        approvers: ['cfo'],
        nextStep: 'wf-nh-5',
        conditions: ['Banda salarial aprobada', 'Equity (si aplica) validado'],
      },
      {
        id: 'wf-nh-5',
        order: 5,
        name: 'Contrato laboral',
        description: 'Legal redacta el contrato de trabajo según la legislación chilena.',
        responsibleAgent: 'legal-contracts-specialist',
        approvers: ['clo'],
        nextStep: 'wf-nh-6',
        requiredTools: ['Contract Management'],
      },
      {
        id: 'wf-nh-6',
        order: 6,
        name: 'Alta en BUK y sistemas',
        description: 'Payroll Manager crea al empleado en BUK. IT configura accesos.',
        responsibleAgent: 'hr-payroll-manager',
        nextStep: 'wf-nh-7',
        requiredTools: ['BUK Employees', 'BUK Payroll'],
      },
      {
        id: 'wf-nh-7',
        order: 7,
        name: 'Onboarding del empleado',
        description: 'L&D Manager ejecuta el plan de onboarding. HRBP acompaña la integración.',
        responsibleAgent: 'hr-training-manager',
        nextStep: null,
        requiredTools: ['LMS Platform'],
      },
    ],
  },

  // ── CICLO DE NÓMINA ──────────────────────────────────────
  {
    id: 'wf-payroll-cycle',
    name: 'Ciclo de Nómina Mensual',
    description: 'Procesamiento mensual de la nómina. Desde la recolección de novedades hasta el pago.',
    departments: ['hr', 'finance'],
    trigger: 'Día 20 de cada mes (inicio de proceso)',
    sla: 'Nómina pagada antes del último día hábil del mes',
    steps: [
      {
        id: 'wf-pay-1',
        order: 1,
        name: 'Recolección de novedades',
        description: 'Recopilar horas extra, ausencias, vacaciones, bonos variables del período.',
        responsibleAgent: 'hr-payroll-manager',
        nextStep: 'wf-pay-2',
        requiredTools: ['BUK Overtime', 'BUK Absences', 'BUK Vacations'],
      },
      {
        id: 'wf-pay-2',
        order: 2,
        name: 'Cálculo de liquidaciones',
        description: 'Procesar la nómina en BUK con todas las novedades.',
        responsibleAgent: 'hr-payroll-manager',
        nextStep: 'wf-pay-3',
        requiredTools: ['BUK Payroll', 'BUK Employees'],
      },
      {
        id: 'wf-pay-3',
        order: 3,
        name: 'Revisión y aprobación de nómina',
        description: 'CHRO y CFO revisan los totales de nómina antes de autorizar el pago.',
        responsibleAgent: 'chro',
        approvers: ['cfo'],
        nextStep: 'wf-pay-4',
        conditions: ['Sin errores detectados', 'Variación vs mes anterior justificada'],
      },
      {
        id: 'wf-pay-4',
        order: 4,
        name: 'Ejecución de pagos',
        description: 'Tesorería ejecuta las transferencias bancarias de sueldos.',
        responsibleAgent: 'finance-treasurer',
        nextStep: 'wf-pay-5',
        requiredTools: ['Chipax'],
      },
      {
        id: 'wf-pay-5',
        order: 5,
        name: 'Contabilización',
        description: 'Contabilidad registra el asiento de nómina y concilia con BUK.',
        responsibleAgent: 'finance-accountant',
        nextStep: null,
        requiredTools: ['NetSuite', 'BUK Payroll Reconciliation'],
      },
    ],
  },

  // ── OFFBOARDING ──────────────────────────────────────────
  {
    id: 'wf-offboarding',
    name: 'Proceso de Desvinculación',
    description: 'Flujo de salida de un empleado, voluntaria o involuntaria.',
    departments: ['hr', 'finance', 'legal', 'technology'],
    trigger: 'Renuncia del empleado o decisión de desvinculación',
    sla: '15 días hábiles para completar el proceso',
    steps: [
      {
        id: 'wf-off-1',
        order: 1,
        name: 'Evaluación legal de desvinculación',
        description: 'Labor Relations valida el tipo de desvinculación y calcula indemnizaciones.',
        responsibleAgent: 'hr-labor-relations',
        approvers: ['clo'],
        nextStep: 'wf-off-2',
        requiredTools: ['BUK Employees'],
      },
      {
        id: 'wf-off-2',
        order: 2,
        name: 'Cálculo de finiquito',
        description: 'Payroll Manager calcula el finiquito en BUK (vacaciones proporcionales, indemnización, etc.).',
        responsibleAgent: 'hr-payroll-manager',
        nextStep: 'wf-off-3',
        requiredTools: ['BUK Payroll', 'BUK Vacations'],
      },
      {
        id: 'wf-off-3',
        order: 3,
        name: 'Revocación de accesos',
        description: 'IT revoca todos los accesos del empleado a sistemas.',
        responsibleAgent: 'tech-devops-lead',
        nextStep: 'wf-off-4',
        requiredTools: ['Supabase Admin'],
      },
      {
        id: 'wf-off-4',
        order: 4,
        name: 'Pago de finiquito',
        description: 'Tesorería procesa el pago del finiquito.',
        responsibleAgent: 'finance-treasurer',
        nextStep: 'wf-off-5',
        requiredTools: ['Chipax'],
      },
      {
        id: 'wf-off-5',
        order: 5,
        name: 'Baja en BUK y entrevista de salida',
        description: 'HRBP conduce entrevista de salida. Se da de baja en BUK.',
        responsibleAgent: 'hr-hrbp-senior',
        nextStep: null,
        requiredTools: ['BUK Employees'],
      },
    ],
  },

  // ── DESARROLLO DE FEATURE ────────────────────────────────
  {
    id: 'wf-feature-development',
    name: 'Desarrollo de Feature',
    description: 'Ciclo completo de desarrollo de una nueva funcionalidad del producto.',
    departments: ['technology', 'operations'],
    trigger: 'Feature priorizada en el roadmap por Product Manager',
    sla: 'Según estimación del equipo (1-4 sprints)',
    steps: [
      {
        id: 'wf-feat-1',
        order: 1,
        name: 'Discovery y especificación',
        description: 'Product Manager define el problema, propuesta de valor y user stories.',
        responsibleAgent: 'tech-product-manager',
        nextStep: 'wf-feat-2',
      },
      {
        id: 'wf-feat-2',
        order: 2,
        name: 'Diseño técnico',
        description: 'Engineering Manager y CTO definen la arquitectura y approach técnico.',
        responsibleAgent: 'tech-engineering-manager',
        approvers: ['cto'],
        nextStep: 'wf-feat-3',
      },
      {
        id: 'wf-feat-3',
        order: 3,
        name: 'Revisión de seguridad y privacidad',
        description: 'Security Engineer y DPO revisan implicaciones de seguridad y datos.',
        responsibleAgent: 'tech-security-engineer',
        approvers: ['legal-data-privacy'],
        nextStep: 'wf-feat-4',
      },
      {
        id: 'wf-feat-4',
        order: 4,
        name: 'Desarrollo e implementación',
        description: 'El equipo de ingeniería construye la feature (frontend + backend + integrations).',
        responsibleAgent: 'tech-frontend-lead',
        nextStep: 'wf-feat-5',
        requiredTools: ['GitHub', 'BUK SDK', 'Supabase'],
      },
      {
        id: 'wf-feat-5',
        order: 5,
        name: 'QA y testing',
        description: 'QA Lead ejecuta pruebas de calidad, regresión y performance.',
        responsibleAgent: 'tech-qa-lead',
        nextStep: 'wf-feat-6',
      },
      {
        id: 'wf-feat-6',
        order: 6,
        name: 'Deploy a producción',
        description: 'DevOps Lead despliega a producción en Vercel.',
        responsibleAgent: 'tech-devops-lead',
        nextStep: null,
        requiredTools: ['Vercel', 'GitHub Actions'],
      },
    ],
  },

  // ── GESTIÓN DE INCIDENTES ────────────────────────────────
  {
    id: 'wf-incident-management',
    name: 'Gestión de Incidentes',
    description: 'Respuesta y resolución de incidentes de producción.',
    departments: ['technology', 'operations', 'support'],
    trigger: 'Alerta de monitoreo o reporte de cliente',
    sla: 'P1: <15min respuesta, <1h resolución. P2: <1h respuesta, <4h resolución.',
    steps: [
      {
        id: 'wf-inc-1',
        order: 1,
        name: 'Detección y triage',
        description: 'Support o monitoreo detecta el incidente. Se clasifica severidad.',
        responsibleAgent: 'support-team-lead',
        nextStep: 'wf-inc-2',
      },
      {
        id: 'wf-inc-2',
        order: 2,
        name: 'Diagnóstico técnico',
        description: 'DevOps y Technical Support diagnostican la causa raíz.',
        responsibleAgent: 'tech-devops-lead',
        nextStep: 'wf-inc-3',
        requiredTools: ['Application Logs', 'Supabase Admin', 'Vercel'],
      },
      {
        id: 'wf-inc-3',
        order: 3,
        name: 'Resolución y fix',
        description: 'Engineering implementa el fix y DevOps despliega.',
        responsibleAgent: 'tech-engineering-manager',
        nextStep: 'wf-inc-4',
        requiredTools: ['GitHub', 'Vercel'],
      },
      {
        id: 'wf-inc-4',
        order: 4,
        name: 'Comunicación a clientes',
        description: 'Support comunica la resolución a los clientes afectados.',
        responsibleAgent: 'support-team-lead',
        nextStep: 'wf-inc-5',
      },
      {
        id: 'wf-inc-5',
        order: 5,
        name: 'Post-mortem',
        description: 'COO lidera el post-mortem para prevenir recurrencia.',
        responsibleAgent: 'coo',
        nextStep: null,
      },
    ],
  },

  // ── SOLICITUD DE VACACIONES ──────────────────────────────
  {
    id: 'wf-vacation-request',
    name: 'Solicitud de Vacaciones',
    description: 'Flujo de solicitud y aprobación de vacaciones de un empleado.',
    departments: ['hr'],
    trigger: 'Empleado solicita vacaciones',
    sla: 'Respuesta en <3 días hábiles',
    steps: [
      {
        id: 'wf-vac-1',
        order: 1,
        name: 'Solicitud del empleado',
        description: 'El empleado registra su solicitud de vacaciones.',
        responsibleAgent: 'hr-payroll-manager',
        nextStep: 'wf-vac-2',
        requiredTools: ['BUK Vacations'],
      },
      {
        id: 'wf-vac-2',
        order: 2,
        name: 'Validación de saldo y aprobación',
        description: 'Se verifica el saldo de vacaciones en BUK y el jefe directo aprueba.',
        responsibleAgent: 'hr-payroll-manager',
        nextStep: 'wf-vac-3',
        requiredTools: ['BUK Vacations', 'BUK Employees'],
      },
      {
        id: 'wf-vac-3',
        order: 3,
        name: 'Registro y notificación',
        description: 'Se registra en BUK y se notifica al equipo.',
        responsibleAgent: 'hr-payroll-manager',
        nextStep: null,
        requiredTools: ['BUK Vacations'],
      },
    ],
  },

  // ── REVISIÓN DE CONTRATOS ────────────────────────────────
  {
    id: 'wf-contract-review',
    name: 'Revisión de Contratos',
    description: 'Revisión legal de contratos con clientes o proveedores.',
    departments: ['legal', 'sales', 'operations'],
    trigger: 'Nuevo contrato o renovación requiere revisión legal',
    sla: '<48 horas para revisión estándar, <5 días para contratos complejos',
    steps: [
      {
        id: 'wf-cr-1',
        order: 1,
        name: 'Solicitud de revisión',
        description: 'Sales o Vendor Manager solicita revisión legal.',
        responsibleAgent: 'legal-contracts-specialist',
        nextStep: 'wf-cr-2',
      },
      {
        id: 'wf-cr-2',
        order: 2,
        name: 'Revisión legal',
        description: 'Contracts Specialist revisa términos, riesgos y compliance.',
        responsibleAgent: 'legal-contracts-specialist',
        nextStep: 'wf-cr-3',
        requiredTools: ['Contract Management'],
      },
      {
        id: 'wf-cr-3',
        order: 3,
        name: 'Revisión de privacidad (si aplica)',
        description: 'DPO revisa cláusulas de datos personales si el contrato involucra datos.',
        responsibleAgent: 'legal-data-privacy',
        nextStep: 'wf-cr-4',
      },
      {
        id: 'wf-cr-4',
        order: 4,
        name: 'Aprobación del CLO',
        description: 'CLO aprueba contratos de alto valor o riesgo.',
        responsibleAgent: 'clo',
        nextStep: null,
        conditions: ['Contrato >$50K anual o cláusulas no estándar'],
      },
    ],
  },

  // ── CIERRE FINANCIERO MENSUAL ────────────────────────────
  {
    id: 'wf-financial-close',
    name: 'Cierre Financiero Mensual',
    description: 'Proceso de cierre contable mensual.',
    departments: ['finance', 'hr'],
    trigger: 'Primer día hábil del mes siguiente',
    sla: '3 días hábiles para cierre completo',
    steps: [
      {
        id: 'wf-fc-1',
        order: 1,
        name: 'Conciliación de nómina',
        description: 'Contabilidad concilia nómina de BUK con registros contables.',
        responsibleAgent: 'finance-accountant',
        nextStep: 'wf-fc-2',
        requiredTools: ['NetSuite', 'BUK Payroll Reconciliation'],
      },
      {
        id: 'wf-fc-2',
        order: 2,
        name: 'Conciliaciones bancarias',
        description: 'Contabilidad concilia todas las cuentas bancarias.',
        responsibleAgent: 'finance-accountant',
        nextStep: 'wf-fc-3',
      },
      {
        id: 'wf-fc-3',
        order: 3,
        name: 'Ajustes y provisiones',
        description: 'Controller registra ajustes contables y provisiones.',
        responsibleAgent: 'finance-controller',
        nextStep: 'wf-fc-4',
        requiredTools: ['NetSuite'],
      },
      {
        id: 'wf-fc-4',
        order: 4,
        name: 'Estados financieros y reporting',
        description: 'Controller genera P&L, Balance y Cash Flow. FP&A genera análisis.',
        responsibleAgent: 'finance-controller',
        nextStep: 'wf-fc-5',
      },
      {
        id: 'wf-fc-5',
        order: 5,
        name: 'Revisión del CFO',
        description: 'CFO revisa y aprueba los estados financieros del mes.',
        responsibleAgent: 'cfo',
        nextStep: null,
      },
    ],
  },

  // ── CUSTOMER ONBOARDING ──────────────────────────────────
  {
    id: 'wf-customer-onboarding',
    name: 'Onboarding de Cliente',
    description: 'Proceso de activación de un nuevo cliente en la plataforma.',
    departments: ['support', 'technology', 'sales'],
    trigger: 'Contrato firmado por nuevo cliente',
    sla: '14 días hasta activación completa',
    steps: [
      {
        id: 'wf-co-1',
        order: 1,
        name: 'Handoff de Sales a CS',
        description: 'Account Executive transfiere el cliente al equipo de Customer Success.',
        responsibleAgent: 'sales-account-executive',
        nextStep: 'wf-co-2',
      },
      {
        id: 'wf-co-2',
        order: 2,
        name: 'Configuración técnica',
        description: 'Onboarding Specialist configura la cuenta e integración BUK del cliente.',
        responsibleAgent: 'support-onboarding-specialist',
        nextStep: 'wf-co-3',
        requiredTools: ['BUK API (Setup)', 'Onboarding Database'],
      },
      {
        id: 'wf-co-3',
        order: 3,
        name: 'Capacitación de usuarios',
        description: 'Onboarding Specialist capacita a los usuarios del cliente.',
        responsibleAgent: 'support-onboarding-specialist',
        nextStep: 'wf-co-4',
      },
      {
        id: 'wf-co-4',
        order: 4,
        name: 'Activación y seguimiento',
        description: 'CSM toma la cuenta y verifica que el cliente esté usando el producto.',
        responsibleAgent: 'support-csm-senior',
        nextStep: null,
      },
    ],
  },

  // ── LANZAMIENTO DE CAMPAÑA ───────────────────────────────
  {
    id: 'wf-campaign-launch',
    name: 'Lanzamiento de Campaña de Marketing',
    description: 'Proceso de planificación y ejecución de una campaña de marketing.',
    departments: ['marketing', 'sales'],
    trigger: 'Campaña aprobada en planning trimestral',
    sla: '2-4 semanas desde aprobación hasta lanzamiento',
    steps: [
      {
        id: 'wf-cl-1',
        order: 1,
        name: 'Estrategia y briefing',
        description: 'CMO define objetivos, audiencia y mensajes clave.',
        responsibleAgent: 'cmo',
        nextStep: 'wf-cl-2',
      },
      {
        id: 'wf-cl-2',
        order: 2,
        name: 'Creación de contenido',
        description: 'Content Lead crea los assets de la campaña.',
        responsibleAgent: 'mkt-content-lead',
        nextStep: 'wf-cl-3',
      },
      {
        id: 'wf-cl-3',
        order: 3,
        name: 'Configuración de canales',
        description: 'Digital Manager configura campañas en plataformas de ads.',
        responsibleAgent: 'mkt-digital-manager',
        nextStep: 'wf-cl-4',
        requiredTools: ['Ad Platforms'],
      },
      {
        id: 'wf-cl-4',
        order: 4,
        name: 'Lanzamiento y monitoreo',
        description: 'Growth Analyst monitorea performance y optimiza en tiempo real.',
        responsibleAgent: 'mkt-growth-analyst',
        nextStep: null,
        requiredTools: ['Analytics Platform', 'A/B Testing'],
      },
    ],
  },

  // ── REVISIÓN DE PERFORMANCE ──────────────────────────────
  {
    id: 'wf-performance-review',
    name: 'Evaluación de Desempeño',
    description: 'Ciclo de evaluación de desempeño semestral.',
    departments: ['hr'],
    trigger: 'Junio y Diciembre de cada año',
    sla: '4 semanas para completar el ciclo',
    steps: [
      {
        id: 'wf-pr-1',
        order: 1,
        name: 'Preparación y comunicación',
        description: 'CHRO lanza el ciclo de evaluación y comunica el proceso.',
        responsibleAgent: 'chro',
        nextStep: 'wf-pr-2',
      },
      {
        id: 'wf-pr-2',
        order: 2,
        name: 'Autoevaluación y evaluación del líder',
        description: 'HRBP facilita el proceso de evaluación bidireccional.',
        responsibleAgent: 'hr-hrbp-senior',
        nextStep: 'wf-pr-3',
      },
      {
        id: 'wf-pr-3',
        order: 3,
        name: 'Calibración',
        description: 'CHRO y líderes de departamento calibran las evaluaciones.',
        responsibleAgent: 'chro',
        nextStep: 'wf-pr-4',
      },
      {
        id: 'wf-pr-4',
        order: 4,
        name: 'Feedback y planes de desarrollo',
        description: 'L&D Manager diseña planes de desarrollo basados en resultados.',
        responsibleAgent: 'hr-training-manager',
        nextStep: null,
        requiredTools: ['BUK Employees', 'LMS Platform'],
      },
    ],
  },

  // ── APROBACIÓN DE PRESUPUESTO ────────────────────────────
  {
    id: 'wf-budget-approval',
    name: 'Aprobación de Presupuesto',
    description: 'Proceso de aprobación de presupuestos departamentales o de proyectos.',
    departments: ['finance', 'executive'],
    trigger: 'Solicitud de presupuesto por un departamento',
    sla: '5 días hábiles para presupuestos estándar',
    steps: [
      {
        id: 'wf-ba-1',
        order: 1,
        name: 'Análisis de FP&A',
        description: 'FP&A analiza la solicitud, impacto en P&L y cash flow.',
        responsibleAgent: 'finance-fp-analyst',
        nextStep: 'wf-ba-2',
        requiredTools: ['FP&A Database'],
      },
      {
        id: 'wf-ba-2',
        order: 2,
        name: 'Recomendación del CFO',
        description: 'CFO revisa el análisis y da su recomendación.',
        responsibleAgent: 'cfo',
        nextStep: 'wf-ba-3',
      },
      {
        id: 'wf-ba-3',
        order: 3,
        name: 'Aprobación del CEO',
        description: 'CEO aprueba presupuestos >$50K.',
        responsibleAgent: 'ceo',
        nextStep: null,
        conditions: ['Presupuesto >$50K requiere aprobación CEO'],
      },
    ],
  },

  // ── SECURITY REVIEW ──────────────────────────────────────
  {
    id: 'wf-security-review',
    name: 'Revisión de Seguridad',
    description: 'Revisión de seguridad para nuevos features, integraciones o cambios de infraestructura.',
    departments: ['technology', 'legal'],
    trigger: 'Nuevo feature que maneja datos sensibles o nueva integración',
    sla: '3 días hábiles',
    steps: [
      {
        id: 'wf-sr-1',
        order: 1,
        name: 'Threat modeling',
        description: 'Security Engineer realiza threat modeling del cambio.',
        responsibleAgent: 'tech-security-engineer',
        nextStep: 'wf-sr-2',
      },
      {
        id: 'wf-sr-2',
        order: 2,
        name: 'Evaluación de privacidad',
        description: 'DPO evalúa el impacto en datos personales.',
        responsibleAgent: 'legal-data-privacy',
        nextStep: 'wf-sr-3',
      },
      {
        id: 'wf-sr-3',
        order: 3,
        name: 'Aprobación del CTO',
        description: 'CTO aprueba los resultados de la revisión de seguridad.',
        responsibleAgent: 'cto',
        nextStep: null,
      },
    ],
  },
];
